// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuIFALnYFqQJkii3j1N-OxiSbEFazhAns',
    appId: '1:992872967513:web:7d2c8ab464bd8be6663048',
    messagingSenderId: '992872967513',
    projectId: 'dicoding-flutter-e73ea',
    authDomain: 'dicoding-flutter-e73ea.firebaseapp.com',
    storageBucket: 'dicoding-flutter-e73ea.firebasestorage.app',
    measurementId: 'G-B345NWW2VN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuImdmL128-4mAXaJNsRidKEFN54AmLec',
    appId: '1:992872967513:android:9d7efbe91f374b7a663048',
    messagingSenderId: '992872967513',
    projectId: 'dicoding-flutter-e73ea',
    storageBucket: 'dicoding-flutter-e73ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAn5tKxqT5UjocIfAM91tFjvuDH1NZOK8',
    appId: '1:992872967513:ios:4fd107423037a2fc663048',
    messagingSenderId: '992872967513',
    projectId: 'dicoding-flutter-e73ea',
    storageBucket: 'dicoding-flutter-e73ea.firebasestorage.app',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
